### ISSUE TITLE
Old files in outputs are not properly deleted

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#1946]
**Long Story Short**

After I create a first file in my jupyter lab, it properly appears in the outputs in osparc outputs AND in servicedata

Then I create more files in the same outputs folder, and there is a zip file appearing the outputs AND in the service data.
What is incorrect is that the old file is still in the service data.

**Expected Behavior**

The old single file should be deleted and I should only see the zip file

**Actual behaviour**

both zip and 1st file is visible in service data.

**Steps to reproduce**

- create jupyter lab
- go to output_1 folder
- create a file
- wait until it appears, check also in service data dialog
- create a second file
- wait until it appears, check in service data
--> the 1st file is still around

**Environment**

**Additional context**

![Image](https://github.com/user-attachments/assets/637ccd19-8acb-4d56-ada4-4226b1cd18d7)

**Comment by GitHK** [comment]
- this was recently fixed with https://github.com/ITISFoundation/osparc-simcore/pull/7301

**Comment by Konohana0608** [comment]
Is somebody working on this? This is still not fixed, and it actually confused me quite a bit. In the Nimbus Pilot trial, I saw two output files where there should only have been one.  I first thought that I made a mistake in my service's internal data handling. After a while, I found out that this is an osparc bug.... @GitHK @sanderegg 

<img width="1032" height="722" alt="Image" src="https://github.com/user-attachments/assets/b2ef5a97-b0d2-4f7d-bdb9-0353f7191a3c" />

<img width="792" height="803" alt="Image" src="https://github.com/user-attachments/assets/84ea609a-9271-4e34-a1e1-a63a2c9fbf5c" />

**Comment by sanderegg** [comment]
@Konohana0608 I put it in the milestone so it appears in my dashboard if I manage to get time we can have a look at it.

**Comment by Konohana0608** [comment]
amazing thank you so much @sanderegg <3
